apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-qa-worker
  namespace: ai-qa-production
  labels:
    app: ai-qa-worker
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ai-qa-worker
  template:
    metadata:
      labels:
        app: ai-qa-worker
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9108"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: worker
        image: yourusername/ai-qa-agent:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9108
          protocol: TCP
        env:
        - name: WORKER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-qa-secrets
              key: api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-qa-secrets
              key: openai-api-key
        - name: PERCY_TOKEN
          valueFrom:
            secretKeyRef:
              name: ai-qa-secrets
              key: percy-token
        - name: WORKER_LOG_LEVEL
          value: "INFO"
        - name: WORKER_ENABLE_METRICS
          value: "true"
        - name: RUNNER_REPORTS_DIR
          value: "/app/reports"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: reports
          mountPath: /app/reports
        - name: data
          mountPath: /app/data
      volumes:
      - name: reports
        persistentVolumeClaim:
          claimName: ai-qa-reports-pvc
      - name: data
        persistentVolumeClaim:
          claimName: ai-qa-data-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-qa-worker-service
  namespace: ai-qa-production
  labels:
    app: ai-qa-worker
spec:
  type: ClusterIP
  selector:
    app: ai-qa-worker
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9108
    targetPort: 9108
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-qa-reports-pvc
  namespace: ai-qa-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-qa-data-pvc
  namespace: ai-qa-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-qa-worker-hpa
  namespace: ai-qa-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-qa-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
